fixes + removed final field stuff due to a "java.lang.NoSuchMethodError" on server + fixed last remaining Platinum reverse recipes for Dreamcraft/GT Items + fixed a typo in the centrifuge recipe + added a circuit priorisation mode for the MEGA EBF + redid the CircuitAssemblyLine Structure-Check + version increase to match testing version
Signed-off-by: bartimaeusnek <33183715+bartimaeusnek@users.noreply.github.com>

Former-commit-id: 7037b78d15f87115e9064f712aaacd523d9784d6